#!/bin/bash

echo "Type the letter corresponding to you desired action:"
echo <<EOF
	a. Display a list of currently logged-in users. 
	b. Display the system’s host name. 
	c. Display the time and date. 
	d. Display the disk usage.
	e. Display the current working directory. 
	f. Display the pathname to the BASH shell.
EOF
